// Getting edits out of the browser and back into the repo.
//
// This is a static site with nowhere to POST, so the level editor and the
// icon editor both write to localStorage — which is per-device and
// impermanent. Exchange is the bridge: it turns what's in localStorage into
// *exactly the text a repo file should contain*, so committing an edit is a
// whole-file replace rather than a hand-merge into the middle of something.
// Import is the same trip backwards, for moving edits between devices or
// restoring after a browser clears its storage.
//
// Pure text in, pure text out — no clipboard, no DOM, no storage. Whoever
// calls it decides how the text actually travels (see modals.js).

import { parseLevel } from "./level.js";
import { BUILDINGS } from "./buildings.js";
import { ICON_GRID_SIZE } from "./icons.js";

export const LEVELS_FILENAME = "levels.json";
export const ICONS_FILENAME = "icons-data.js";

// The complete contents of levels/levels.json for the given level list —
// shipped levels with locally-saved ones already merged in, which is what
// game.js's levelList already holds. Two-space JSON, matching the file as
// committed, so the diff shows only what actually changed.
export function exportLevelsText(levels) {
  return JSON.stringify(levels, null, 2) + "\n";
}

// The complete contents of icons-data.js. JSON is a subset of JS, so the
// object literal is just stringified — no hand-rolled JS emitter to get
// wrong. Only types that actually have an icon are written out.
export function exportIconsText(icons) {
  const kept = {};
  for (const id of Object.keys(BUILDINGS)) {
    if (icons[id]) kept[id] = icons[id];
  }
  return [
    "// Custom icons that ship with the game — see the notes in the copy of",
    "// this file in the repo. Generated by the in-game export; paste it over",
    "// icons-data.js and commit.",
    "",
    "export const SHIPPED_ICONS = " + JSON.stringify(kept, null, 2) + ";",
    "",
  ].join("\n");
}

function isIconRows(value) {
  return (
    Array.isArray(value) &&
    value.length === ICON_GRID_SIZE &&
    value.every(
      (row) =>
        typeof row === "string" &&
        row.length === ICON_GRID_SIZE &&
        /^[#.]+$/.test(row)
    )
  );
}

// Pulls the icon map out of exported text. Accepts either the raw JSON object
// or the whole icons-data.js file — pasting the file you were just handed
// should work, not just the fragment inside it.
function extractIconsJson(text) {
  const trimmed = text.trim();
  if (trimmed.startsWith("{")) return trimmed;
  const match = trimmed.match(/SHIPPED_ICONS\s*=\s*(\{[\s\S]*\})\s*;?\s*$/);
  if (!match) return null;
  return match[1];
}

// Works out what was pasted and validates it, or throws with a reason that
// says what's actually wrong. Levels arrive as a JSON array, icons as an
// object (or the whole icons-data.js file) — distinguishable on sight, so
// there's no mode to pick first and no way to pick it wrong.
//
// Returns { kind: "levels", levels } or { kind: "icons", icons }.
export function parseImport(text) {
  if (!text || !text.trim()) throw new Error("Nothing to import");

  const iconsJson = extractIconsJson(text);
  if (iconsJson !== null) {
    let parsed;
    try {
      parsed = JSON.parse(iconsJson);
    } catch (error) {
      throw new Error(`Not valid JSON: ${error.message}`);
    }
    const icons = {};
    for (const [id, rows] of Object.entries(parsed)) {
      if (!BUILDINGS[id]) throw new Error(`Unknown building type '${id}'`);
      if (!isIconRows(rows)) {
        throw new Error(
          `Icon for '${id}' must be ${ICON_GRID_SIZE} rows of ${ICON_GRID_SIZE} '#' or '.' characters`
        );
      }
      icons[id] = rows;
    }
    return { kind: "icons", icons };
  }

  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (error) {
    throw new Error(`Not valid JSON: ${error.message}`);
  }
  if (!Array.isArray(parsed)) {
    throw new Error("Expected a levels array or an icons object");
  }
  // Validate every level before accepting any of them, using the same parser
  // the game itself uses — a half-imported set would be worse than none.
  parsed.forEach((record, i) => {
    if (!record || typeof record.name !== "string" || !record.name) {
      throw new Error(`Level ${i} needs a non-empty name`);
    }
    try {
      parseLevel(record);
    } catch (error) {
      throw new Error(`Level '${record.name}': ${error.message}`);
    }
  });
  return { kind: "levels", levels: parsed };
}
